name: Daily Update

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 3 AM UTC
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  update_database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the desired Python version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Ensure you have a requirements.txt file

    - name: Run update script
      run: |
        python update_db_script.py  # Replace with your script name

    - name: Upload Logs
      if: failure()  # Only upload logs if the script fails
      uses: actions/upload-artifact@v3
      with:
        name: error-logs
        path: |
          path/to/your/log/file.log  # Adjust as needed
